# Generated by Django 4.0.4 on 2022-05-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSCUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32)),
                ('occupation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=32)),
                ('discover_data', models.DateField(auto_now=True)),
                ('picture', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('catgories', models.CharField(choices=[('Reptiles', 'Reptiles'), ('Flying Avian Animals', 'Flying Avian Animals'), ('Mammals', 'Mammals'), ('Insects', 'Insects'), ('Poultry', 'Poultry'), ('Fishes', 'Fishes'), ('Carnivores', 'Carnivores'), ('Other', 'Other')], default='Other', max_length=32)),
                ('discoverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.cscuser')),
            ],
        ),
    ]
