# Generated by Django 4.0.4 on 2022-05-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='Animal',
        ),
        migrations.AlterModelTable(
            name='cscuser',
            table='CSCUser',
        ),
    ]
